import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  topPane: {
    width: '100%',
    height: 70,
    padding: 15,
    backgroundColor: '#231B37',
    borderBottomRightRadius: 25,
    borderBottomLeftRadius: 25,
    shadowColor: 'black',
    shadowRadius: 5,
    shadowOffset: {top: -20, width: 0, height: 0},
    elevation: 8,
    shadowOpacity: 0.95,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  centerPane: {
    //flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: 15,
    height: '100%',
  },
  bottomPane: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F4F6FF',
    borderBottomStartRadius: 80,
    borderTopRightRadius: 80,
  },
  profilePicBig: {
    position: 'absolute',
    top: 90,
    left: 30,
    height: 120,
    width: 120,
    borderRadius: 60,
    backgroundColor: 'white',
    borderWidth: 5,
    borderColor: '#1B152A',
    shadowColor: 'black',
    shadowRadius: 4,
    shadowOffset: {top: 0, width: 0, height: 0},
    elevation: 8,
    shadowOpacity: 0.2,
  },
  profilePicSmall: {
    position: 'absolute',
    top: 5,
    left: 10,
    height: 60,
    width: 60,
    borderRadius: 30,
    backgroundColor: 'white',
    borderWidth: 5,
    borderColor: '#1B152A',
    shadowColor: 'black',
    shadowRadius: 4,
    shadowOffset: {top: 0, width: 0, height: 0},
    elevation: 8,
    shadowOpacity: 0.2,
  },
});
